### PR TITLE
Added search functionality

### PR DESCRIPTION
**Pull request by phrogg**
Hey
I love your app but I missed the function to filter for something. So I made this. :) Thanks for your great work!

### CODE REVIEW

**Comment by SirPryderi** [comment]
Thank you for your PR! I'll get this one built and merged ASAP. Good job with the translations as well. 💯

**Comment by phrogg** [comment]
> Thank you for your PR! I'll get this one built and merged ASAP. Good job with the translations as well. 💯

Thanks a lot :)

**Comment by SirPryderi** [comment]
Hey, @phrogg, I was having a look at the PR, do you think you could add something before the search results that makes obvious that you're have an ongoing search? 

Something like this would be cool: 
image

If you don't have time/don't want to, it's okay, I'll probably do that at some point.

**Comment by phrogg** [comment]
> Hey, @phrogg, I was having a look at the PR, do you think you could add something before the search results that makes obvious that you're have an ongoing search?
> 
> Something like this would be cool:
> image
> 
> If you don't have time/don't want to, it's okay, I'll probably do that at some point.

I will have a look at it. I mean it shouldn't be too hard. But I will do that when I have the time. May take some days :) I'll just give an update here when done :)

**Comment by SirPryderi** [comment]
Thank you very much! 🙏 I'm dusting the app a bit, and trying to set up CI with Travis. :)

Let me know if you decide not to make the changes, and I'll merge it as it is.

**Comment by phrogg** [comment]
> Thank you very much!  I'm dusting the app a bit, and trying to set up CI with Travis. :)
> 
> Let me know if you decide not to make the changes, and I'll merge it as it is.

Hey, have a look at it and tell me what you think. :)

**Comment by SirPryderi** [comment]
The new bar looks really great, thank you, @phrogg! I'm happy to merge. 

There are a few conflicts with master now, they should be fairly easy to resolve. I don't think I can fix them myself as I can't push on your branch. 

They should be easy to fix, tho. Just run `git merge origin/master`, and then accept both changes for the two strings files, while activity_main should be like this (when resolved):

```xml
        <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay" />

        <include layout="@layout/fragment_searchbar" />

    </com.google.android.material.appbar.AppBarLayout>

    <include layout="@layout/fragment_hostrule_list" />
```

If you are okay with that, I will add you as a contributor in the about page. :) 

Thank you again for your PR! 🥇

**Comment by phrogg** [comment]
> The new bar looks really great, thank you, @phrogg! I'm happy to merge.
Thanks :)
> There are a few conflicts with master now, they should be fairly easy to resolve. I don't think I can fix them myself as I can't push on your branch.
> 
> They should be easy to fix, tho. Just run `git merge origin/master`, and then accept both changes for the two strings files, while activity_main should be like this (when resolved):
> 
I resolved them via the web interface, I thought why not give it a shot, right?
> 
> If you are okay with that, I will add you as a contributor in the about page. :)
> 
I would be super happy :)
> 
> Thank you again for your PR! 🥇
> 
Thank you for the app in the first place 🥇

**Pull request merged**
